# Generated by Django 5.2.7 on 2026-01-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aktivnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_aktivnosti', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('datum', models.DateField()),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volonteri.kategorija')),
            ],
        ),
    ]
