# Generated by Django 5.2.7 on 2026-01-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volonteri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('datum_prijave', models.DateTimeField(auto_now_add=True)),
                ('aktivnost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volonteri.aktivnost')),
            ],
        ),
    ]
